//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ApplicationBeverage.
const (
	Beer    ApplicationBeverage = "beer"
	Spirits ApplicationBeverage = "spirits"
	Wine    ApplicationBeverage = "wine"
)

// Defines values for VerdictStatus.
const (
	MISMATCH VerdictStatus = "MISMATCH"
	NOTFOUND VerdictStatus = "NOT_FOUND"
	REVIEW   VerdictStatus = "REVIEW"
	SKIPPED  VerdictStatus = "SKIPPED"
	VERIFIED VerdictStatus = "VERIFIED"
)

// Application What the application filed. Every field is what was filed, not what the label prints.
type Application struct {
	// Abv Alcohol content, percent by volume
	Abv *float64 `json:"abv,omitempty"`

	// Aliases Other names the application itself states for a claim
	Aliases  *map[string][]string `json:"aliases,omitempty"`
	Beverage ApplicationBeverage  `json:"beverage"`
	Brand    *string              `json:"brand,omitempty"`

	// Class The class or type designation
	Class *string `json:"class,omitempty"`

	// NetMl Net contents, millilitres
	NetMl  *float64 `json:"net_ml,omitempty"`
	Origin *string  `json:"origin,omitempty"`

	// Producer The permittee's name, then its address, one line each
	Producer *[]string `json:"producer,omitempty"`
}

// ApplicationBeverage defines model for Application.Beverage.
type ApplicationBeverage string

// Error defines model for Error.
type Error struct {
	// Error What went wrong, in a sentence a person can act on
	Error string `json:"error"`
}

// Evidence Why the verdict is what it is.
type Evidence struct {
	// Competitor The nearest reading of a different value
	Competitor         *string  `json:"competitor,omitempty"`
	CompetitorDistance *float64 `json:"competitor_distance,omitempty"`

	// Confidence The recogniser's own confidence in the reading
	Confidence *float64 `json:"confidence,omitempty"`

	// Crop A PNG of the region, so the reviewer sees what the engine saw
	Crop *[]byte `json:"crop,omitempty"`

	// Distance How far apart they are, as a share of the claim's length
	Distance *float64 `json:"distance,omitempty"`

	// Matched The accepted spelling it was compared to
	Matched *string `json:"matched,omitempty"`

	// Parts How many detections were joined to make the reading
	Parts *int `json:"parts,omitempty"`

	// Radius What that distance had to be inside
	Radius *float64 `json:"radius,omitempty"`

	// Read The text the recogniser read there
	Read   *string `json:"read,omitempty"`
	Region *Region `json:"region,omitempty"`
}

// Health defines model for Health.
type Health struct {
	Detail *string `json:"detail,omitempty"`

	// Engine What produced a verdict. A verdict is worth what its provenance is worth.
	Engine *Identity `json:"engine,omitempty"`
	Ready  bool      `json:"ready"`
}

// Identity What produced a verdict. A verdict is worth what its provenance is worth.
type Identity struct {
	Commit     *string `json:"commit,omitempty"`
	CommitTime *string `json:"commit_time,omitempty"`
	Go         *string `json:"go,omitempty"`

	// Models SHA-256 of each model the binary carries, from the bytes it runs
	Models *map[string]string `json:"models,omitempty"`

	// Modified The tree had uncommitted changes when this was built
	Modified *bool   `json:"modified,omitempty"`
	Version  *string `json:"version,omitempty"`
}

// Region defines model for Region.
type Region struct {
	H *int `json:"h,omitempty"`
	W *int `json:"w,omitempty"`
	X *int `json:"x,omitempty"`
	Y *int `json:"y,omitempty"`
}

// Result defines model for Result.
type Result struct {
	Claims []Verdict `json:"claims"`

	// Emphasis The warning's header, in capitals and heavier than the body
	Emphasis *[]Verdict `json:"emphasis,omitempty"`

	// Engine What produced a verdict. A verdict is worth what its provenance is worth.
	Engine Identity `json:"engine"`

	// LatencyMs Wall clock for this verification
	LatencyMs int `json:"latency_ms"`

	// Reason Present when the label could not be read at all
	Reason *string `json:"reason,omitempty"`

	// Reference The statutory warning
	Reference *[]Verdict `json:"reference,omitempty"`

	// Stages Where the time went, in milliseconds.
	Stages *Stages `json:"stages,omitempty"`
}

// Stages Where the time went, in milliseconds.
type Stages struct {
	Boxes      *int `json:"boxes,omitempty"`
	Decide     *int `json:"decide,omitempty"`
	Detect     *int `json:"detect,omitempty"`
	Recognise  *int `json:"recognise,omitempty"`
	RunCount   *int `json:"run_count,omitempty"`
	Runs       *int `json:"runs,omitempty"`
	TurnedPass *int `json:"turned_pass,omitempty"`
}

// Verdict defines model for Verdict.
type Verdict struct {
	Claim string `json:"claim"`

	// Evidence Why the verdict is what it is.
	Evidence *Evidence `json:"evidence,omitempty"`
	Expected string    `json:"expected"`
	Observed *string   `json:"observed,omitempty"`
	Reason   *string   `json:"reason,omitempty"`

	// Status VERIFIED — the label carries what was filed.
	// MISMATCH — the label carries something else, named in `observed`.
	// REVIEW — read, but not clearly enough to decide.
	// NOT_FOUND — not found on the label.
	// SKIPPED — not required for this beverage.
	Status VerdictStatus `json:"status"`
}

// VerdictStatus VERIFIED — the label carries what was filed.
// MISMATCH — the label carries something else, named in `observed`.
// REVIEW — read, but not clearly enough to decide.
// NOT_FOUND — not found on the label.
// SKIPPED — not required for this beverage.
type VerdictStatus string

// VerifyMultipartBody defines parameters for Verify.
type VerifyMultipartBody struct {
	// Claims The filed application, as JSON — an Application
	Claims string `json:"claims"`

	// Image The label, as PNG or JPEG
	Image openapi_types.File `json:"image"`
}

// VerifyMultipartRequestBody defines body for Verify for multipart/form-data ContentType.
type VerifyMultipartRequestBody VerifyMultipartBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Whether the service is ready, and which build it is
	// (GET /health)
	Health(w http.ResponseWriter, r *http.Request)
	// This document
	// (GET /openapi.yaml)
	Spec(w http.ResponseWriter, r *http.Request)
	// Verify one label against the claims filed for it
	// (POST /verify)
	Verify(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Health operation middleware
func (siw *ServerInterfaceWrapper) Health(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Health(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Spec operation middleware
func (siw *ServerInterfaceWrapper) Spec(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Spec(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Verify operation middleware
func (siw *ServerInterfaceWrapper) Verify(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Verify(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/health", wrapper.Health)
	m.HandleFunc("GET "+options.BaseURL+"/openapi.yaml", wrapper.Spec)
	m.HandleFunc("POST "+options.BaseURL+"/verify", wrapper.Verify)

	return m
}
